### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by shiyuw09** [haochaco/issue-tracker-zh#85]
无法打开 app，报错：
Uncaught Exception:
Error: ENOENT: no such file or directory, mkdir '/Users/wangsy/Library/Application Support/Tea/analytics'
    at Object.mkdirSync (fs.js:731:3)
    at t.n._init (/Applications/Tea.app/Contents/Resources/app.asar/src/build/main.prod.js:2:29214)
    at t.n [as constructor] (/Applications/Tea.app/Contents/Resources/app.asar/src/build/main.prod.js:2:28516)
    at new t (/Applications/Tea.app/Contents/Resources/app.asar/src/build/main.prod.js:2:31096)
    at new e.exports (/Applications/Tea.app/Contents/Resources/app.asar/src/build/main.prod.js:2:26736)
    at Object.<anonymous> (/Applications/Tea.app/Contents/Resources/app.asar/src/build/main.prod.js:224:117053)
    at C (/Applications/Tea.app/Contents/Resources/app.asar/src/build/main.prod.js:1:6990)
    at r (/Applications/Tea.app/Contents/Resources/app.asar/src/build/main.prod.js:1:840)
    at Object.<anonymous> (/Applications/Tea.app/Contents/Resources/app.asar/src/build/main.prod.js:128:71424)
    at C (/Applications/Tea.app/Contents/Resources/app.asar/src/build/main.prod.js:1:6990)

**Comment by shiyuw09** [comment]
macOS Mojave Version 10.14
MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by shiyuw09** [comment]
手动创建 ~/Library/Application Support/Tea/analytics 目录之后可以运行
